### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by flamendless** [MusouCrow/ParticleEditor#1]
Hi, after cloning and running "love ." command in your project, it just gives this error

> Error: src/editor/interface.lua:82: bad argument #1 to 'NewFrame' (string expected, got table)

Platform: Manjaro Linux (64-bit)

**Comment by MusouCrow** [comment]
I am sorry, the editor only supports Windows (32 bit), Mac OS X and Ubuntu (64 bit) now.
But you can compile the [imgui](https://github.com/slages/love-imgui.git) and [cjson](https://github.com/mpx/lua-cjson.git) by yourself.
Thanks for your issue :)

**Comment by flamendless** [comment]
The README lists Ubuntu under the cross-platform feature though :/
